name: Provar_API

on: [push] #Executa la acció en cada push

jobs: #Especifica les tasques de la accio
prova-api:
  runs-on: ubuntu-latest

  steps:
    -name: Checkout del repo
    uses: actions/checkout@v4

    -name: Instala Python
    uses: actions/setup-python@v4
    whith: 
    python-version: 3.8

    -name: Instala Flask
    run: |
      python -m pip install --upgrade pip
      pip install Flask -y

    -name: Inicia les aplicacions 
    run: |
      api_calculadora.py &
      calculadora.py &
    -name: Prova l'API
    run: |
      #Deixem un temps per que tot s'inicii com toca
      sleep 5
      curl -s http://localhost:5000/suma/5/3 | grep -q "8" && echo "SUMA OK" || echo "SUMA MALAMENT"
      curl -s http://localhost:5000/resta/5/3 | grep -q "2" && echo "RESTA OK" || echo "RESTA MALAMENT"
      curl -s http://localhost:5000/multiplica/5/3 | grep -q "15" && echo "MULTIPLICA OK" || echo "MULTIPLICA MALAMENT"
      curl -s http://localhost:5000/divideix/6/3 | grep -q "2" && echo "DIVIDEIX OK" || echo "DIVIDEIX MALAMENT"
